[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_drop_blog = "5e2TUn4NnhCWkoCFHZJXPPtpEHW1fz7T1S9FtPqo7yxq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/khanhhuy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
